In [ ]:
%matplotlib inline 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore')

In [ ]:
df1 = pd.read_csv("/content/students(1).csv")
df2 = pd.read_csv("/content/students(2).csv")

df1

id school sex  age address famsize Pstatus  Medu  Fedu      Mjob  \
0      1     GP   1   18       U     NaN       A     4     4   at_home   
1      2     GP   1   17       U     NaN       T     1     1   at_home   
2      3     GP   1   15       U     NaN       T     1     1   at_home   
3      4     GP   1   15       U     GT3       T     4     2    health   
4      5     GP   1   16       U     GT3       T     3     3     other   
..   ...    ...  ..  ...     ...     ...     ...   ...   ...       ...   
390  391     MS   M   20       U     LE3       A     2     2  services   
391  392     MS   M   17       U     NaN       T     3     1  services   
392  393     MS   M   21       R     NaN       T     1     1     other   
393  394     MS   M   18       R     NaN       T     3     2  services   
394  395     MS   M   19       U     NaN       T     1     1     other   

         Fjob  reason guardian  traveltime  studytime  failures schoolsup  \
0     teacher  course   mother           2          2         0       yes   
1       other     NaN   father           1          2         0        no   
2       other   other   mother           1          2         3       yes   
3    services     NaN   mother           1          3         0        no   
4       other     NaN   father           1          2         0        no   
..        ...     ...      ...         ...        ...       ...       ...   
390  services  course    other           1          2         2        no   
391  services     NaN   mother           2          1         0        no   
392     other     NaN    other           1          1         3        no   
393     other     NaN   mother           3          1         0        no   
394   at_home     NaN   father           1          1         0        no   

    famsup  
0       no  
1      yes  
2       no  
3      yes  
4      yes  
..     ...  
390    yes  
391     no  
392     no  
393     no  
394     no  

[395 rows x 18 columns]

In [ ]:
df2

id paid activities nursery higher internet romantic  famrel  freetime  \
0      1   no         no     yes    NaN       no       no       4         3   
1      2   no         no      no    NaN      yes       no       5         3   
2      3  yes         no     yes    NaN      yes       no       4         3   
3      4  yes        yes     yes    yes      yes      yes       3         2   
4      5  yes         no     yes    yes       no       no       4         3   
..   ...  ...        ...     ...    ...      ...      ...     ...       ...   
390  391  yes         no     yes    NaN       no       no       5         5   
391  392   no         no      no    NaN      yes       no       2         4   
392  393   no         no      no    NaN       no       no       5         5   
393  394   no         no      no    yes      yes       no       4         4   
394  395   no         no     yes    NaN      yes       no       3         2   

     goout  Dalc  Walc health  absences  G1  G2  G3  
0        4     1     1      ?         6   5   6   6  
1        3     1     1      ?         4   5   5   6  
2        2     2     3      ?        10   7   8  10  
3        2     1     1      ?         2  15  14  15  
4        2     1     2      ?         4   6  10  10  
..     ...   ...   ...    ...       ...  ..  ..  ..  
390      4     4     5      ?        11   9   9   9  
391      5     3     4      ?         3  14  16  16  
392      3     3     3      ?         3  10   8   7  
393      1     3     4      ?         0  11  12  10  
394      3     3     3      ?         5   8   9   9  

[395 rows x 17 columns]

In [ ]:
df = pd.merge(df1, df2, on=['id'])

In [ ]:
df.describe()

id         age        Medu        Fedu  traveltime   studytime  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean   198.000000   16.696203    2.749367    2.521519    1.448101    2.035443   
std    114.170924    1.276043    1.094735    1.088201    0.697505    0.839240   
min      1.000000   15.000000    0.000000    0.000000    1.000000    1.000000   
25%     99.500000   16.000000    2.000000    2.000000    1.000000    1.000000   
50%    198.000000   17.000000    3.000000    2.000000    1.000000    2.000000   
75%    296.500000   18.000000    4.000000    3.000000    2.000000    2.000000   
max    395.000000   22.000000    4.000000    4.000000    4.000000    4.000000   

         failures      famrel    freetime       goout        Dalc        Walc  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean     0.334177    3.944304    3.235443    3.108861    1.481013    2.291139   
std      0.743651    0.896659    0.998862    1.113278    0.890741    1.287897   
min      0.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      0.000000    4.000000    3.000000    2.000000    1.000000    1.000000   
50%      0.000000    4.000000    3.000000    3.000000    1.000000    2.000000   
75%      0.000000    5.000000    4.000000    4.000000    2.000000    3.000000   
max      3.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  395.000000  395.000000  395.000000  395.000000  
mean     5.708861   10.908861   10.713924   10.415190  
std      8.003096    3.319195    3.761505    4.581443  
min      0.000000    3.000000    0.000000    0.000000  
25%      0.000000    8.000000    9.000000    8.000000  
50%      4.000000   11.000000   11.000000   11.000000  
75%      8.000000   13.000000   13.000000   14.000000  
max     75.000000   19.000000   19.000000   20.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 395 entries, 0 to 394
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          395 non-null    int64 
 1   school      395 non-null    object
 2   sex         395 non-null    object
 3   age         395 non-null    int64 
 4   address     395 non-null    object
 5   famsize     157 non-null    object
 6   Pstatus     395 non-null    object
 7   Medu        395 non-null    int64 
 8   Fedu        395 non-null    int64 
 9   Mjob        395 non-null    object
 10  Fjob        395 non-null    object
 11  reason      66 non-null     object
 12  guardian    395 non-null    object
 13  traveltime  395 non-null    int64 
 14  studytime   395 non-null    int64 
 15  failures    395 non-null    int64 
 16  schoolsup   395 non-null    object
 17  famsup      395 non-null    object
 18  paid        395 non-null    object
 19  activities  395 non-null    object
 20  nursery   

In [ ]:
df.isnull().sum()

id              0
school          0
sex             0
age             0
address         0
famsize       238
Pstatus         0
Medu            0
Fedu            0
Mjob            0
Fjob            0
reason        329
guardian        0
traveltime      0
studytime       0
failures        0
schoolsup       0
famsup          0
paid            0
activities      0
nursery         0
higher        322
internet        0
romantic        0
famrel          0
freetime        0
goout           0
Dalc            0
Walc            0
health          0
absences        0
G1              0
G2              0
G3              0
dtype: int64

In [ ]:
df['famsize'].value_counts()

GT3    117
LE3     40
Name: famsize, dtype: int64

In [ ]:
df['famsize'].fillna(value=df['famsize'].mode()[0], inplace=True)

In [ ]:
df['famsize'].value_counts()

GT3    355
LE3     40
Name: famsize, dtype: int64

In [ ]:
df['higher'].fillna(value=df['higher'].mode()[0], inplace=True)

In [ ]:
df['higher'].value_counts()

yes    392
no       3
Name: higher, dtype: int64

In [ ]:
df['reason'].value_counts()

course        34
home          15
reputation    13
other          4
Name: reason, dtype: int64

In [ ]:
df['reason'].fillna(value=df['reason'].mode()[0], inplace=True)

In [ ]:
for col in df.columns:
    print(col)
    print(df[f'{col}'].unique())
    print('*'*75)

id
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246

In [ ]:
df['sex'] = df['sex'].replace('1', 'F')


In [ ]:
df['sex'].value_counts()

F    208
M    187
Name: sex, dtype: int64

In [ ]:
df['health'].value_counts()

?    383
5      6
4      3
2      2
3      1
Name: health, dtype: int64

In [ ]:
df[df['health']== '5']

id school sex  age address famsize Pstatus  Medu  Fedu      Mjob  ...  \
45    46     GP   F   15       U     LE3       A     4     3     other  ...   
133  134     GP   F   16       U     GT3       A     3     4  services  ...   
138  139     GP   M   16       U     GT3       T     1     1  services  ...   
176  177     GP   F   16       U     GT3       T     2     2  services  ...   
249  250     GP   M   16       U     GT3       T     0     2     other  ...   
275  276     GP   F   17       U     GT3       T     2     2  services  ...   

    famrel freetime goout  Dalc  Walc  health absences  G1  G2  G3  
45       5        2     2     1     1       5        8   8   8   6  
133      3        2     1     1     4       5       16  12  11  11  
138      4        4     4     1     3       5        0  14  12  12  
176      3        4     4     1     4       5        2  13  13  11  
249      4        3     2     2     4       5        0  13  15  15  
275      4        4     4     2     3       5        6  12  12  12  

[6 rows x 34 columns]

In [ ]:
df = df.drop(columns = 'health')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          395 non-null    int64 
 1   school      395 non-null    object
 2   sex         395 non-null    object
 3   age         395 non-null    int64 
 4   address     395 non-null    object
 5   famsize     395 non-null    object
 6   Pstatus     395 non-null    object
 7   Medu        395 non-null    int64 
 8   Fedu        395 non-null    int64 
 9   Mjob        395 non-null    object
 10  Fjob        395 non-null    object
 11  reason      395 non-null    object
 12  guardian    395 non-null    object
 13  traveltime  395 non-null    int64 
 14  studytime   395 non-null    int64 
 15  failures    395 non-null    int64 
 16  schoolsup   395 non-null    object
 17  famsup      395 non-null    object
 18  paid        395 non-null    object
 19  activities  395 non-null    object
 20  nursery   

In [ ]:
df.head(10)

id school sex  age address famsize Pstatus  Medu  Fedu      Mjob  ...  \
0   1     GP   F   18       U     GT3       A     4     4   at_home  ...   
1   2     GP   F   17       U     GT3       T     1     1   at_home  ...   
2   3     GP   F   15       U     GT3       T     1     1   at_home  ...   
3   4     GP   F   15       U     GT3       T     4     2    health  ...   
4   5     GP   F   16       U     GT3       T     3     3     other  ...   
5   6     GP   M   16       U     LE3       T     4     3  services  ...   
6   7     GP   M   16       U     LE3       T     2     2     other  ...   
7   8     GP   F   17       U     GT3       A     4     4     other  ...   
8   9     GP   M   15       U     GT3       A     3     2  services  ...   
9  10     GP   M   15       U     GT3       T     3     4     other  ...   

  romantic famrel freetime  goout  Dalc  Walc absences  G1  G2  G3  
0       no      4        3      4     1     1        6   5   6   6  
1       no      5        3      3     1     1        4   5   5   6  
2       no      4        3      2     2     3       10   7   8  10  
3      yes      3        2      2     1     1        2  15  14  15  
4       no      4        3      2     1     2        4   6  10  10  
5       no      5        4      2     1     2       10  15  15  15  
6       no      4        4      4     1     1        0  12  12  11  
7       no      4        1      4     1     1        6   6   5   6  
8       no      4        2      2     1     1        0  16  18  19  
9       no      5        5      1     1     1        0  14  15  15  

[10 rows x 33 columns]

In [ ]:
df.columns

Index(['id', 'school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu',
       'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [ ]:
df = df.astype(str)


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          395 non-null    object
 1   school      395 non-null    object
 2   sex         395 non-null    object
 3   age         395 non-null    object
 4   address     395 non-null    object
 5   famsize     395 non-null    object
 6   Pstatus     395 non-null    object
 7   Medu        395 non-null    object
 8   Fedu        395 non-null    object
 9   Mjob        395 non-null    object
 10  Fjob        395 non-null    object
 11  reason      395 non-null    object
 12  guardian    395 non-null    object
 13  traveltime  395 non-null    object
 14  studytime   395 non-null    object
 15  failures    395 non-null    object
 16  schoolsup   395 non-null    object
 17  famsup      395 non-null    object
 18  paid        395 non-null    object
 19  activities  395 non-null    object
 20  nursery   

In [ ]:
df = df.drop(columns = 'id')

In [ ]:
df['G1'] = df['G1'].astype('float64')
df['G2'] = df['G2'].astype('float64')
df['G3'] = df['G3'].astype('float64')

In [ ]:
# Defining a function to find the statistical relationship with all the categorical variables
def FunctionAnova(inpData, TargetVariable, CategoricalPredictorList):
    from scipy.stats import f_oneway

    # Creating an empty list of final selected predictors
    SelectedPredictors=[]
    
    print('##### ANOVA Results ##### \n')
    for predictor in CategoricalPredictorList:
        CategoryGroupLists=inpData.groupby(predictor)[TargetVariable].apply(list)
        AnovaResults = f_oneway(*CategoryGroupLists)
        
        # If the ANOVA P-Value is <0.05, that means we reject H0
        if (AnovaResults[1] < 0.05):
            print(predictor, 'is correlated with', TargetVariable, '| P-Value:', AnovaResults[1])
            SelectedPredictors.append(predictor)
        else:
            print(predictor, 'is NOT correlated with', TargetVariable, '| P-Value:', AnovaResults[1])
    
    return(SelectedPredictors)

In [ ]:
# Calling the function to check which categorical variables are correlated with target
# Calling the function to check which categorical variables are correlated with target
CategoricalPredictorList=['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu',
       'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'absences']
FunctionAnova(inpData=df, 
              TargetVariable='G3', 
              CategoricalPredictorList=CategoricalPredictorList)

##### ANOVA Results ##### 

school is NOT correlated with G3 | P-Value: 0.3722262371311368
sex is correlated with G3 | P-Value: 0.039865332341527955
age is correlated with G3 | P-Value: 0.024801338949217662
address is correlated with G3 | P-Value: 0.035632679756558636
famsize is NOT correlated with G3 | P-Value: 0.8957096082585791
Pstatus is NOT correlated with G3 | P-Value: 0.25005293926392647
Medu is correlated with G3 | P-Value: 9.241876816630144e-05
Fedu is correlated with G3 | P-Value: 0.0221972905719672
Mjob is correlated with G3 | P-Value: 0.005194749939407733
Fjob is NOT correlated with G3 | P-Value: 0.2683141692179647
reason is NOT correlated with G3 | P-Value: 0.9183103129430642
guardian is NOT correlated with G3 | P-Value: 0.2051326420058259
traveltime is NOT correlated with G3 | P-Value: 0.13937884626846256
studytime is NOT correlated with G3 | P-Value: 0.1607228096836598
failures is correlated with G3 | P-Value: 1.6421656015988342e-12
schoolsup is NOT correlated with G3 | 

['sex',
 'age',
 'address',
 'Medu',
 'Fedu',
 'Mjob',
 'failures',
 'paid',
 'romantic',
 'goout',
 'absences']

In [ ]:
SelectedColumns=['sex','age', 'address', 'Medu', 'Fedu', 'Mjob', 'failures', 'paid', 'romantic', 'goout', 'absences','G1','G2','G3']

# Selecting final columns
df=df[SelectedColumns]
df.head()

sex age address Medu Fedu     Mjob failures paid romantic goout absences  \
0   F  18       U    4    4  at_home        0   no       no     4        6   
1   F  17       U    1    1  at_home        0   no       no     3        4   
2   F  15       U    1    1  at_home        3  yes       no     2       10   
3   F  15       U    4    2   health        0  yes      yes     2        2   
4   F  16       U    3    3    other        0  yes       no     2        4   

     G1    G2    G3  
0   5.0   6.0   6.0  
1   5.0   5.0   6.0  
2   7.0   8.0  10.0  
3  15.0  14.0  15.0  
4   6.0  10.0  10.0

In [ ]:
from sklearn.preprocessing import LabelEncoder
# create a label encoder object
le = LabelEncoder()

# apply label encoding to each categorical variable
df['sex'] = le.fit_transform(df['sex'])
df['Mjob'] = le.fit_transform(df['Mjob'])
df['paid'] = le.fit_transform(df['paid'])
df['romantic'] = le.fit_transform(df['romantic'])
df['age'] = le.fit_transform(df['age'])
df['Medu'] = le.fit_transform(df['Medu'])
df['Fedu'] = le.fit_transform(df['Fedu'])
df['failures'] = le.fit_transform(df['failures'])
df['goout'] = le.fit_transform(df['goout'])

In [ ]:
df['address'] = le.fit_transform(df['address'])

In [ ]:
df['Mjob'].value_counts()

2    141
3    103
0     59
4     58
1     34
Name: Mjob, dtype: int64

In [ ]:
df['paid'].value_counts()

0    214
1    181
Name: paid, dtype: int64

In [ ]:
df['sex'] = df['sex'].astype('category')
df['Mjob'] = df['Mjob'].astype('category')
df['paid'] = df['paid'].astype('category')
df['romantic'] = df['romantic'].astype('category')
df['address'] = df['address'].astype('category')

df['age'] = df['age'].astype('category')
df['Medu'] = df['Medu'].astype('category')
df['Fedu'] = df['Fedu'].astype('category')
df['failures'] = df['failures'].astype('category')
df['goout'] = df['goout'].astype('category')
df['absences'] = df['absences'].astype('float64')

In [ ]:
df3 = df.sample(frac = 1)

In [ ]:
X = np.array(df3.drop(["G3"],1))
print("Shape of X:",X.shape)
print(X)

Shape of X: (395, 13)
[[ 1.  0.  1. ...  6. 11. 13.]
 [ 1.  4.  1. ... 38.  8.  9.]
 [ 0.  4.  1. ...  0. 10.  9.]
 ...
 [ 1.  3.  0. ...  2. 13. 12.]
 [ 1.  1.  1. ...  0. 13. 15.]
 [ 0.  3.  0. ... 10. 14. 12.]]


In [ ]:
y = np.array(df3["G3"])
print("Shape of y:",y.shape)
print(y)

Shape of y: (395,)
[14.  8.  0.  6. 11.  0.  7. 11.  5.  8.  9.  0.  0.  0.  9. 16.  0. 15.
 10.  8. 12. 11.  5. 16. 10. 14. 11.  9. 14.  7. 15. 11. 10. 12. 15.  0.
 11.  8.  9. 13.  8. 12. 13.  0. 13. 11. 13. 18. 12. 10. 16. 12. 17. 12.
 10.  8.  0. 14.  9. 11. 12.  9. 12.  9. 10. 11.  9.  8. 16. 10. 11. 17.
 17. 13. 10. 11. 13.  7.  0. 10.  0.  9. 15.  7. 13. 12. 16. 19.  0. 11.
  6. 10. 10.  0. 15. 15. 13.  8.  9.  0. 15.  5. 11. 17.  9. 18. 10.  8.
  8. 14. 16.  0.  6. 11. 10.  0.  6.  9. 11.  8. 13. 17.  8. 14. 15. 16.
  8. 14. 14. 18. 11. 10.  9. 10. 13.  9. 18. 16. 13. 16.  0. 10.  0. 18.
 10. 10. 13.  6. 12. 10. 13. 14. 18.  7. 15. 10.  9. 14.  0.  0.  9. 19.
 10. 14. 18. 15. 12. 10. 10.  9. 18. 16. 10.  6. 10. 15. 10. 10. 15.  8.
 14. 10. 13.  9. 10.  6. 11. 13. 12. 10.  8. 11. 12. 14. 10. 15. 11. 11.
  5. 11. 12. 12. 14.  8. 15.  9. 14. 15.  8. 14. 12.  8. 13.  8.  9.  8.
 15.  8. 16.  0. 11. 15. 13.  6. 11.  8. 12. 10.  0. 10.  7. 12.  0.  6.
 12.  6. 11. 10.  9. 12. 10. 13.

In [ ]:
size = X.shape[0]
X_train = X[:int(0.7 * size),:]
X_test = X[int(0.7 * size):,:]
y_train = y[:int(0.7 * size)]
y_test = y[int(0.7 * size):]

In [ ]:

#Standardizing the X_train and X_test daatsets
mu = np.mean(X_train, 0)
sigma = np.std(X_train, 0)

X_train = (X_train - mu ) / sigma

#We use the same mean and SD as the one of X_train as we dont know the mean of X_test
X_test = (X_test - mu ) / sigma

#Standardizing the y_train data
mu_y = np.mean(y_train, 0)
sigma_y = np.std(y_train, 0, ddof = 0)

y_train = (y_train - mu_y ) / sigma_y

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(276, 13)
(119, 13)
(276,)
(119,)


In [ ]:
y_train = y_train.reshape(len(y_train),1)
y_test = y_test.reshape(len(y_test),1)
y_pred = np.zeros(y_test.shape)
y_train.shape, y_test.shape,y_pred.shape

((276, 1), (119, 1), (119, 1))

In [ ]:
n_neigh = 3
for row in range(len(X_test)):
    euclidian_distance = np.sqrt(np.sum((X_train - X_test[row])**2, axis = 1 ))
    y_pred[row] = np.mean(y_train[np.argsort(euclidian_distance, axis = 0)[:n_neigh]])* sigma_y + mu_y
    
#Finding the root mean squared error 

RMSE = np.sqrt(np.mean((y_pred - y_test)**2))
print(RMSE)

3.3122583064583213


In [ ]:
# Calculate mean absolute error
mae = np.mean(np.abs(y_test - y_pred))

print("Mean Absolute Error:", mae)

Mean Absolute Error: 2.3529411764705883


In [ ]:
# We are setting a range of K values and calculating the RMSE for each of them. This way we can chose the optimal K value
k_list = [x for x in range(1,50,1)]

# Calculating the distance matrix using numpy broadcasting technique 
distance = np.sqrt(((X_train[:, :, None] - X_test[:, :, None].T) ** 2).sum(1))

#Sorting each data points of the distance matrix to reduce computational effort 
sorted_distance = np.argsort(distance, axis = 0)

#The knn function takes in the sorted distance and returns the RMSE of the 
def knn(X_train,X_test,y_train,y_test,sorted_distance,k):
    y_pred = np.zeros(y_test.shape)
    for row in range(len(X_test)):
        
        #Transforming the y_train values to adjust the scale. 
        y_pred[row] = np.mean(y_train[sorted_distance[:,row][:k]])* sigma_y + mu_y

    RMSE = np.sqrt(np.mean((y_test - y_pred)**2))
    return RMSE

#Storing the RMSE values in a list for each k value 
rmse_list = []
for i in k_list:
    rmse_list.append(knn(X_train,X_test,y_train,y_test,sorted_distance,i))

In [ ]:
#Finding the optimal K value
min_rmse_k_value = k_list[rmse_list.index(min(rmse_list))]

#Finding the lowest possible RMSE
optimal_RMSE = knn(X_train,X_test,y_train,y_test,sorted_distance,min_rmse_k_value)
optimal_RMSE

2.9784569201361952

In [ ]:
min_rmse_k_value

7

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score,mean_absolute_error

print(np.sqrt(mean_squared_error(y_test,y_pred))) 
r2scr = print(r2_score(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))

3.3122583064583213
0.5420372619379823
2.3529411764705883


In [ ]:
from sklearn.neighbors import KNeighborsRegressor
RegModel = KNeighborsRegressor(n_neighbors=3)


In [ ]:
from sklearn.model_selection import GridSearchCV
param={'n_neighbors': range(1,50)}
grid_kn=GridSearchCV(estimator=RegModel,param_grid=param,scoring='neg_mean_squared_error',cv=5,verbose=1,n_jobs=-1)
grid_kn.fit(X_train,y_train)
print('Best K For Model is: ',grid_kn.best_params_)
print('Best Score is: ',grid_kn.best_score_)

Fitting 5 folds for each of 49 candidates, totalling 245 fits
Best K For Model is:  {'n_neighbors': 9}
Best Score is:  -0.3804218748610015


In [ ]:
RegModel = KNeighborsRegressor(n_neighbors=7)

In [ ]:
KNN=RegModel.fit(X_train,y_train)
prediction=KNN.predict(X_test)

In [ ]:
from sklearn import metrics
# Measuring Goodness of fit in Training data
print('R2 Value:',metrics.r2_score(y_train, KNN.predict(X_train)))

R2 Value: 0.7164505482629153
